'use strict';

const SITES = [
  {
    id: 'ja',
    name: '看JavBus',
    tagline: 'JavBus 内容浏览入口',
    baseUrl: 'https://avjb.com/',
    encoding: 'gbk',
    contentId: { type: 'path', marker: 'video', offset: 1, pattern: '^\\d+$' },
    feeds: [
      { id: 'home', name: '首页', path: '/', isHome: true },
    ],
    pagination: 'none',
    playback: 'avjb-rebuild',
    proxySegments: false,
  },
  {
    id: '18j',
    name: '看18J',
    tagline: '高清片库，支持多清晰度播放',
    baseUrl: 'https://18j.tv/',
    contentId: { type: 'path', marker: 'v', offset: 1, pattern: '^\\d+$' },
    feeds: [
      { id: 'hot', name: '热门', path: '/label/hot/by/time/' },
      { id: 't-1', name: '国产', path: '/t/1/' },
      { id: 't-2', name: '日韩', path: '/t/2/' },
      { id: 't-3', name: '欧美', path: '/t/3/' },
      { id: 't-4', name: '伦理', path: '/t/4/' },
      { id: 't-5', name: '动漫', path: '/t/5/' },
      { id: 't-6', name: '另类', path: '/t/6/' },
      { id: 't-13', name: '吃瓜黑料', path: '/t/13/' },
      { id: 't-14', name: '国产探花', path: '/t/14/' },
      { id: 't-21', name: 'JAV自拍', path: '/t/21/' },
      { id: 't-22', name: '中文字幕', path: '/t/22/' },
      { id: 't-23', name: 'JAV无码', path: '/t/23/' },
    ],
    pagination: 'path',
    playback: 'direct',
  },
  {
    id: 'kan91',
    name: '91porna',
    tagline: '91 自拍原创视频',
    baseUrl: 'https://91porna.com/',
    module: 'kan91',
    feeds: [
      { id: 'home', name: '首页', category: 'play', isHome: true },
      { id: 'play', name: '正在播放', category: 'play' },
      { id: 'now_hot', name: '当前最热', category: 'now_hot' },
      { id: 'new_update', name: '最近更新', category: 'new_update' },
      { id: 'original', name: '原创', category: 'original' },
      { id: 'now_month_hot', name: '本月最热', category: 'now_month_hot' },
      { id: 'ten_minutes', name: '10分钟以上', category: 'ten_minutes' },
      { id: 'twenty_minutes', name: '20分钟以上', category: 'twenty_minutes' },
      { id: 'now_month_collect', name: '本月收藏', category: 'now_month_collect' },
      { id: 'hd', name: '高清', category: 'hd' },
      { id: 'month_hot', name: '每月最热', category: 'month_hot' },
      { id: 'now_month_comment', name: '本月讨论', category: 'now_month_comment' },
      { id: 'max_collect', name: '收藏最多', category: 'max_collect' },
    ],
  },
  {
    id: 'mr',
    name: '麻人电台',
    tagline: '每日大赛与黑料',
    baseUrl: 'https://www.mrds66.com/',
    module: 'mr',
    feeds: [
      { id: 'home', name: '首页', isHome: true },
      { id: 'mrds', name: '每日大赛' },
      { id: 'ztds', name: '主题大赛' },
      { id: 'rstt', name: '热搜吃瓜' },
      { id: 'xazd', name: '校园学生' },
      { id: 'blyp', name: '必撸大赛' },
      { id: 'fctg', name: '反差泄密' },
      { id: 'mhds', name: '网红黑料' },
      { id: 'lqdp', name: '猎奇重口' },
      { id: 'jdsj', name: 'AV看片' },
      { id: 'mxwh', name: '明星大赛' },
      { id: 'smdh', name: '动漫之家' },
      { id: 'dypd', name: '影视国漫' },
    ],
  },
  {
    id: 'tx',
    name: '唐心vlog',
    tagline: '探花偷拍视频',
    baseUrl: 'https://tangxinvlog.pro/',
    module: 'tx',
    feeds: [
      { id: 'home', name: '首页', path: '/', isHome: true },
      { id: 'all', name: '全部', path: '/videos/' },
    ],
  },
  {
    id: 'rou',
    name: '肉肉视频',
    tagline: '国产剧情视频',
    baseUrl: 'https://rou.video/',
    module: 'rou',
    feeds: [
      { id: 'home', name: '首页', path: '/home', isHome: true },
      { id: '国产AV', name: '国产AV', path: '/t/国产AV' },
      { id: '探花', name: '探花', path: '/t/探花' },
      { id: '国产自拍', name: '国产自拍', path: '/t/国产自拍' },
      { id: 'OnlyFans', name: 'OnlyFans', path: '/t/OnlyFans' },
      { id: '成人Vlog', name: '成人Vlog', path: '/t/成人Vlog' },
      { id: '中文字幕', name: '中文字幕', path: '/t/中文字幕' },
      { id: '日本', name: '日本', path: '/t/日本' },
      { id: '中国', name: '中国', path: '/t/中国' },
      { id: '有码系列', name: '有码系列', path: '/t/有码系列' },
      { id: '素人剧情', name: '素人剧情', path: '/t/素人剧情' },
      { id: '丝袜美腿', name: '丝袜美腿', path: '/t/丝袜美腿' },
      { id: '黑料', name: '黑料', path: '/t/黑料' },
      { id: '无码自拍', name: '无码自拍', path: '/t/无码自拍' },
      { id: 'AI视频', name: 'AI视频', path: '/t/AI视频' },
    ],
  },
  {
    id: 'best',
    name: '看Best',
    tagline: 'BestJavPorn 高清片库',
    baseUrl: 'https://www.bestjavporn.com/',
    module: 'best',
    feeds: [
      { id: 'home', name: '首页', isHome: true },
      { id: 'censored', name: '有码', path: '/v25/category/censored/' },
      { id: 'uncensored', name: '无码', path: '/v25/category/uncensored/' },
      { id: 'amateur', name: '素人', path: '/v25/category/amateur/' },
      { id: 'decensored', name: '骑乘位', path: '/v25/category/decensored/' },
      { id: 'english-sub', name: '英字', path: '/v25/category/censored/english-subtitle/' },
      { id: 'chinese-sub', name: '中字', path: '/v25/category/chinese-subtitle/' },
    ],
  },
  {
    id: 'madouai',
    name: '麻豆AI',
    tagline: '麻豆 AI 视频',
    baseUrl: 'https://www.madouai.xyz/',
    module: 'madouai',
    feeds: [
      { id: 'all', name: '全部' },
      { id: '2', name: 'AV - 中文字幕' },
      { id: '1', name: '国产自拍（最新更新）' },
      { id: '27', name: '每日更新' },
      { id: '8', name: 'AV - 无码流出' },
      { id: '21', name: '反差母狗' },
      { id: '13', name: '清纯少女' },
      { id: '10', name: '麻豆x性吧联合原创' },
      { id: '4', name: '探花大神' },
      { id: '7', name: '91大神' },
      { id: '6', name: '麻豆原创AI' },
      { id: '20', name: '破解偷拍' },
      { id: '14', name: '重口调教' },
      { id: '28', name: '世界杯专场' },
      { id: '19', name: '黑料吃瓜' },
      { id: '22', name: '白虎嫩妹' },
      { id: '15', name: '直播大秀' },
      { id: '9', name: '麻豆传媒' },
      { id: '23', name: '家庭乱伦' },
      { id: '16', name: '网红主播' },
      { id: '24', name: '熟女偷情' },
      { id: '17', name: '媚黑母狗' },
      { id: '25', name: '网黄原创' },
      { id: '18', name: '白虎少女' },
    ],
  },
  {
    id: 'madou',
    name: '麻豆',
    tagline: '麻豆传媒等工作室视频',
    baseUrl: 'https://madou.casa/',
    module: 'madou',
    feeds: [
      { id: 'home', name: '首页', isHome: true },
      { id: '_likes', name: '点赞排行' },
      { id: '_week', name: '7天热门' },
      { id: '_month', name: '30天热门' },
      { id: '91制片厂', name: '91制片厂' },
      { id: '爱豆', name: '爱豆' },
      { id: '草莓', name: '草莓' },
      { id: '大鸟十八', name: '大鸟十八' },
      { id: '大象传媒', name: '大象传媒' },
      { id: '抖阴', name: '抖阴' },
      { id: '果冻传媒', name: '果冻传媒' },
      { id: '皇家华人', name: '皇家华人' },
      { id: '精东影业', name: '精东影业' },
      { id: '乐播传媒', name: '乐播传媒' },
      { id: '麻豆传媒', name: '麻豆传媒' },
      { id: '麻豆导演系列', name: '麻豆导演系列' },
      { id: '麻豆番外篇', name: '麻豆番外篇' },
      { id: '麻豆花絮', name: '麻豆花絮' },
      { id: '猫爪影像', name: '猫爪影像' },
      { id: '蜜桃影像', name: '蜜桃影像' },
      { id: '女神羞羞研究所', name: '女神羞羞研究所' },
      { id: '女优淫娃培训营', name: '女优淫娃培训营' },
      { id: '起点传媒-性视界传媒', name: '起点传媒/性视界传媒' },
      { id: '情趣k歌房', name: '情趣K歌房' },
      { id: '天美传媒', name: '天美传媒' },
      { id: '突袭女优家', name: '突袭女优家' },
      { id: '兔子先生', name: '兔子先生' },
      { id: '小鹏奇啪行', name: '小鹏奇啪行' },
      { id: '星空无限传媒', name: '星空无限传媒' },
      { id: '杏吧', name: '杏吧' },
      { id: '淫欲游戏王', name: '淫欲游戏王' },
      { id: 'hongkongdoll', name: 'HongKongDoll' },
      { id: 'kiss糖果屋', name: 'KISS糖果屋' },
      { id: 'psychoporntw', name: 'PsychopornTW' },
      { id: 'sa国际传媒', name: 'SA国际传媒' },
    ],
  },
];

function findSite(id) {
  return SITES.find((s) => s.id === id) || null;
}

function publicImageAllowed(url) {
  if (!url) return false;
  if (/^data:image\//.test(url)) return true;
  return /^https:\/\/(?:[a-z0-9.-]+\.)?(?:imgclh\.com|avstatic\.com|cdn202511\.com|18j2026\.com|jb-aiwei\.cc|cfnav\.com|bestjavporn\.com|vdcdn\.xyz|pianopic\.com|streamhls\.click|streamtape\.net|tapecontent\.net|cloudatacdn\.com)(?:[/?#]|$)/i.test(url);
}

module.exports = { SITES, findSite, publicImageAllowed };
